#data_path: "./data/graph_features_text_no_cd.json"
data: "./sport_data/"
vocab: './sport_data/vocab.txt'
vocab_size: 60000
type_num: 4
head_num: 4
log: './sport_data/log/'
epoch: 5
batch_size: 32
param_init: 0.1
optim: 'adam'
learning_rate: 0.0005
max_grad_norm: 8
window_size: [1,2,3]
filter_size: 128
learning_rate_decay: 0.5
schedule: True
start_decay_at: 2
emb_size: 128
encoder_hidden_size: 128
decoder_hidden_size: 256
num_layers: 2
bidirec: True
dropout: 0.1
max_tgt_len: 30
max_sentence_len: 100
eval_interval: 1000
save_interval: 5000
max_generator_batches: 32
metric: ['bleu', 'xent']
shared_vocab: True
beam_size: 10
